#!/usr/bin/env python3
"""Bake the Monet gallery's floor: oak parquet + its stained border frieze.

A painting gallery is not a white box with a white floor. Every hall that shows
this kind of work — Marmottan, Orsay, the Louvre's Denon rooms — stands on oak
parquet laid point de Hongrie (herringbone) at 45 degrees to the walls, with a
darker stained frieze running around the room against the skirting.

Two tile sets come out of here, seamless in both axes:

  floor_parquet_*   herringbone field, 1.70 m square tile, 12 x 60 cm planks
  floor_border_*    three straight stained boards, 0.85 x 1.92 m tile

The herringbone tiles because the pattern's lattice is generated by
L1 = (N+1, N-1) and L2 = (1, -1) in units of the plank width, and that lattice
contains (2N, 0) and (0, 2N); rotated 45 degrees those two become a square of
side 2N*sqrt(2), which is exactly the tile baked here. Grain is synthesised from
the plank's own (length, width) coordinates, never from a noise image, so it
stays continuous across a plank that runs off one edge and back in the other.
"""
import numpy as np
from PIL import Image
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'textures' / 'cruise-monet'
N = 5                        # plank length / plank width
PW = 0.12                    # plank width, metres
PERIOD = 2 * N               # lattice period, plank widths
TILE_U = PERIOD * np.sqrt(2)         # tile side, plank widths (45 deg frame)
TILE_M = TILE_U * PW                 # tile side, metres (1.697)

BORDER_W, BORDER_L = 0.85, 1.92      # frieze tile, metres
SRGB = np.float32


def srgb(a):
    """Linear 0..1 -> 8-bit sRGB."""
    a = np.clip(a, 0.0, 1.0)
    e = np.where(a <= 0.0031308, a * 12.92, 1.055 * a ** (1 / 2.4) - 0.055)
    return np.clip(e * 255.0 + 0.5, 0, 255).astype(np.uint8)


def to_linear(c):
    c = np.asarray(c, SRGB) / 255.0
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def normal_map(h, strength):
    """Height (tile-periodic) -> tangent-space normal map, wrapped gradients."""
    dx = (np.roll(h, -1, 1) - np.roll(h, 1, 1)) * 0.5 * strength
    dy = (np.roll(h, -1, 0) - np.roll(h, 1, 0)) * 0.5 * strength
    nz = np.ones_like(h)
    inv = 1.0 / np.sqrt(dx * dx + dy * dy + 1.0)
    # +Y of the normal map points up the image; image rows run down.
    rgb = np.stack([-dx * inv, dy * inv, nz * inv], -1)
    return np.clip((rgb * 0.5 + 0.5) * 255.0 + 0.5, 0, 255).astype(np.uint8)


def grain(sl, sw, p, flecks=True):
    """Oak figure for a plank: sl along the length 0..1, sw across 0..1.

    p holds the per-plank draws: ring count, four wobble phases, fleck phase.
    Returns (rings 0..1 dark, fine fibre -1..1, ray flecks 0..1).
    """
    tau = 2 * np.pi
    ringf, p1, p2, p3, p4, p5 = (p[..., i] for i in range(6))
    w = (sw * ringf
         + 0.34 * np.sin(tau * (0.7 * sl + p1))
         + 0.13 * np.sin(tau * (1.9 * sl + p2))
         + 0.05 * np.sin(tau * (4.3 * sl + p3)))
    rings = (0.5 - 0.5 * np.cos(tau * w)) ** (1.6 + 1.6 * p3)
    rings *= 0.45 + 0.55 * (0.5 + 0.5 * np.sin(tau * (0.9 * sl + p1)))
    fine = np.sin(tau * (w * (4.7 + 3.0 * p2) + 0.35 * np.sin(tau * (1.3 * sl + p4)) + p5))
    fine = fine * (0.55 + 0.45 * np.sin(tau * (sl * 2.7 + p2)))
    if not flecks:
        return rings, fine, np.zeros_like(rings)
    # Quarter-sawn oak throws silvery medullary dashes along the grain.
    d = np.sin(tau * (sl * 7.0 + p5 * 3.0)) * np.sin(tau * (w * 1.37 + p4))
    fl = np.clip((np.abs(d) - 0.82) / 0.18, 0, 1) ** 1.5
    return rings, fine, fl


# ---------------------------------------------------------------- herringbone
def herringbone(size):
    """Per-pixel plank coordinates for the 45 degree field tile."""
    ax = (np.arange(size, dtype=SRGB) + 0.5) / size * TILE_U
    X, Y = np.meshgrid(ax, ax)
    c = s = np.sqrt(0.5)
    u, v = c * X + s * Y, -s * X + c * Y          # into the plank frame
    sl = np.zeros_like(u); sw = np.zeros_like(u)
    key = np.full(u.shape, -1, np.int32)
    lo_u, hi_u, lo_v, hi_v = u.min(), u.max(), v.min(), v.max()
    for a in range(-16, 17):
        for b in range(-32, 33):
            ox, oy = (N + 1) * a + b, (N - 1) * a - b
            for kind in (0, 1):
                if kind == 0:
                    x0, x1, y0, y1 = ox, ox + N, oy, oy + 1
                else:
                    x0, x1, y0, y1 = ox + N, ox + N + 1, oy, oy + N
                if x1 < lo_u or x0 > hi_u or y1 < lo_v or y0 > hi_v:
                    continue
                m = (u >= x0) & (u < x1) & (v >= y0) & (v < y1)
                if not m.any():
                    continue
                key[m] = ((ox % PERIOD) * PERIOD + (oy % PERIOD)) * 2 + kind
                if kind == 0:
                    sl[m] = (u[m] - x0) / N; sw[m] = v[m] - y0
                else:
                    sl[m] = (v[m] - y0) / N; sw[m] = u[m] - x0
    assert (key >= 0).all(), 'herringbone left holes'
    return sl, sw, key


def bake_parquet(size=1536, normal_size=1024, rough_size=768):
    sl, sw, key = herringbone(size)
    rng = np.random.default_rng(20260917)
    nkey = PERIOD * PERIOD * 2
    draw = np.stack([
        rng.uniform(4.5, 10.5, nkey),        # rings across the width
        rng.random(nkey), rng.random(nkey), rng.random(nkey),
        rng.random(nkey), rng.random(nkey),
    ], -1).astype(SRGB)
    tone = rng.normal(0.0, 1.0, nkey).astype(SRGB)   # per-plank lightness
    warm = rng.normal(0.0, 1.0, nkey).astype(SRGB)   # per-plank hue drift
    cup = rng.uniform(0.4, 1.0, nkey).astype(SRGB)   # how much each board cups

    p = draw[key]
    rings, fine, fl = grain(sl, sw, p)
    t, wcol, cp = tone[key], warm[key], cup[key]

    # Seams: a dark hairline at the joint with a small bevel shadow either side.
    px_u = TILE_U / size                                   # plank widths / px
    edge = np.minimum(sw, 1.0 - sw)                        # across the plank
    end = np.minimum(sl, 1.0 - sl) * N
    d = np.minimum(edge, end)
    bevel = np.clip(d / 0.017, 0, 1)                       # 2 mm chamfer
    seam = np.clip(d / max(px_u * 1.4, 0.004), 0, 1)       # hairline joint

    base = to_linear([166, 127, 87]).astype(SRGB)          # honey oak
    dark = to_linear([116, 81, 50]).astype(SRGB)           # late-wood ring
    col = base[None, None, :] * np.ones(sl.shape + (3,), SRGB)
    mix = (0.34 + 0.34 * p[..., 1])[..., None] * rings[..., None]
    col = col * (1.0 - mix) + dark[None, None, :] * mix
    col *= (1.0 + 0.115 * t + 0.017 * fine)[..., None]
    col *= np.stack([1.0 + 0.032 * wcol, 1.0 + 0.008 * wcol, 1.0 - 0.042 * wcol], -1)
    col += (0.055 * fl * (1.0 - rings))[..., None] * np.array([1.0, 0.94, 0.80], SRGB)
    col *= (0.58 + 0.42 * bevel)[..., None]                # chamfer shading
    col *= (0.34 + 0.66 * seam)[..., None]                 # the joint itself
    col *= (1.0 - 0.05 * (1.0 - np.clip(end / 0.5, 0, 1)))[..., None]  # end grain drinks stain

    # Height: cupped boards, recessed joints, ring relief the varnish keeps.
    h = (1.0 - bevel) * -0.35 + (1.0 - seam) * -0.65
    h += 0.10 * cp * (1.0 - (2.0 * sw - 1.0) ** 2)
    h += 0.045 * (1.0 - rings) + 0.012 * fine

    # Varnish: satin over the field, matt in the joints, a little polish in
    # the middle of the room where feet have gone for thirty years.
    tau = 2 * np.pi
    ax = (np.arange(size, dtype=SRGB) + 0.5) / size
    gx, gy = np.meshgrid(ax, ax)
    wear = (np.sin(tau * gx + 1.1) * np.sin(tau * gy + 0.4)
            + 0.5 * np.sin(tau * (gx + gy) * 2.0 + 2.2))
    rgh = 0.30 + 0.055 * rings + 0.035 * t + 0.030 * wear
    rgh = np.where(seam < 1.0, rgh + 0.28 * (1.0 - seam), rgh)
    rgh = np.clip(rgh, 0.24, 0.78)

    Image.fromarray(srgb(col)).save(OUT / 'floor_parquet_diffuse.webp', quality=92, method=6)
    Image.fromarray(normal_map(h, 26.0)).resize(
        (normal_size, normal_size), Image.LANCZOS).save(
        OUT / 'floor_parquet_normal.webp', quality=90, method=6)
    Image.fromarray((np.clip(rgh, 0, 1) * 255).astype(np.uint8)).resize(
        (rough_size, rough_size), Image.LANCZOS).save(
        OUT / 'floor_parquet_rough.webp', quality=88, method=6)
    return col


# -------------------------------------------------------------------- frieze
def bake_border(w=512, l=1024):
    """Three stained boards running the length of the frieze, joints staggered."""
    NB = 3
    ax = (np.arange(w, dtype=SRGB) + 0.5) / w * BORDER_W     # across, metres
    ay = (np.arange(l, dtype=SRGB) + 0.5) / l * BORDER_L     # along, metres
    X, Y = np.meshgrid(ax, ay)
    bw = BORDER_W / NB
    bi = np.clip((X / bw).astype(np.int32), 0, NB - 1)
    sw = X / bw - bi                                          # across a board
    # One butt joint per board per tile, staggered by a third of the tile.
    off = np.array([0.0, 1 / 3, 2 / 3], SRGB)[bi]
    sl = (Y / BORDER_L + off) % 1.0

    rng = np.random.default_rng(510)
    nk = NB * 3
    draw = np.stack([
        rng.uniform(3.0, 7.0, nk), rng.random(nk), rng.random(nk),
        rng.random(nk), rng.random(nk), rng.random(nk)], -1).astype(SRGB)
    seg = (bi * 3 + (Y / (BORDER_L / 3)).astype(np.int32) % 3)
    p = draw[seg]
    rings, fine, _ = grain(sl, sw, p, flecks=False)
    tone = rng.normal(0, 1, nk).astype(SRGB)[seg]

    edge = np.minimum(sw, 1.0 - sw) * bw                      # metres to a seam
    endd = np.minimum(sl, 1.0 - sl) * BORDER_L
    d = np.minimum(edge, endd)
    bevel = np.clip(d / 0.005, 0, 1)
    seam = np.clip(d / (BORDER_W / w * 1.4), 0, 1)

    base = to_linear([118, 74, 44]).astype(SRGB)              # stained walnut
    dark = to_linear([62, 36, 20]).astype(SRGB)
    col = base[None, None, :] * np.ones(X.shape + (3,), SRGB)
    col = col * (1 - 0.65 * rings[..., None]) + dark[None, None, :] * (0.65 * rings[..., None])
    col *= (1.0 + 0.085 * tone + 0.025 * fine)[..., None]
    col *= (0.34 + 0.66 * bevel)[..., None]
    col *= (0.18 + 0.82 * seam)[..., None]

    h = (1 - bevel) * -0.5 + (1 - seam) * -0.5 + 0.05 * (1 - rings) + 0.012 * fine
    rgh = np.clip(0.28 + 0.05 * rings + 0.03 * tone + 0.30 * (1 - seam), 0.24, 0.8)

    Image.fromarray(srgb(col)).save(OUT / 'floor_border_diffuse.webp', quality=92, method=6)
    Image.fromarray(normal_map(h, 20.0)).save(OUT / 'floor_border_normal.webp', quality=95, method=6)
    Image.fromarray((rgh * 255).astype(np.uint8)).resize((w // 2, l // 2), Image.LANCZOS).save(
        OUT / 'floor_border_rough.webp', quality=88, method=6)


if __name__ == '__main__':
    bake_parquet()
    bake_border()
    for f in sorted(OUT.glob('floor_*')):
        print(f'{f.name:32} {f.stat().st_size / 1024:7.1f} kB')
    print(f'parquet tile {TILE_M:.3f} m  |  border tile {BORDER_W} x {BORDER_L} m')
